event/__init__.py
import logging
import uuid
from flask import Flask, jsonify, flash, request, redirect, url_for, render_template, send_from_directory, json

from flask_sqlalchemy import SQLAlchemy
from .config import Config
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager
from flask_login import current_user, login_required
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from flask import session
from flask.sessions import SecureCookieSessionInterface

UPLOAD_FOLDER = '/home/vestimy/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

db = SQLAlchemy()
login_manager = LoginManager()
admin = Admin(name='admins')
# security = Security()
mail = Mail()
bootstrap = Bootstrap()

login_manager.login_view = 'security.login'
login_manager.login_message = u"Пожалуйста, авторизируйтесь."
from .forms_security import ExtendedRegisterForm


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    admin.init_app(app, url='/admin', index_view=HomeAdminView(name='Главная'))
    login_manager.init_app(app)
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
    mail.init_app(app)
    bootstrap.init_app(app)

    from .views.main.views import main
    from .views.event.views import events
    from .views.arena.views import arenas
    from .views.artist.views import artists
    from .views.manager.views import managers
    from .views.login.views import logins
    from .views.tour.views import tours
    from .views.api.views import api
    from .views.security.views import security
    from .views.profile.views import profiles
    from .views.message.views import messages
    from .views.friends.views import friends

    app.register_blueprint(main)
    app.register_blueprint(events)
    app.register_blueprint(arenas)
    app.register_blueprint(artists)
    app.register_blueprint(managers)
    app.register_blueprint(tours)
    app.register_blueprint(api)
    app.register_blueprint(security)
    app.register_blueprint(profiles)
    app.register_blueprint(messages)
    app.register_blueprint(friends)

    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    @app.route('/uploads/<filename>')
    def uploaded_file(filename):
        return send_from_directory(app.config['UPLOAD_PHOTO_PROFILES'],
                                   filename)

    @app.route('/photo_profile/<filename>')
    @login_required
    def photo_profile(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_PROFILES,
                                   filename)

    @app.route('/document_profile/<filename>')
    @login_required
    def document_profile(filename):
        return send_from_directory(Config.UPLOAD_DOCUMENTS_PROFILES,
                                   filename)

    @app.route('/img_arena/<img>')
    @login_required
    def img_arena(img):
        return send_from_directory(Config.UPLOAD_PHOTO_ARENA,
                                   img)

    @app.route('/photo_artist/<filename>')
    def photo_artist(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_ARTIST,
                                   filename)

    @app.route('/inspina/<path:filename>')
    def inspina(filename):
        return send_from_directory(Config.UPLOAD_ADMIN,
                                   filename)

    @app.context_processor
    def company_default():
        if current_user.is_authenticated:
            company_default = Company.query.get(current_user.settings.company_default_id)
            if not company_default:
                settings = Settings.query.get(current_user.settings_id)
                settings.company_default_id = current_user.company[0].id
                db.session.commit()
                company_default = Company.query.get(current_user.settings.company_default_id)
            # return dict(company_default=current_user.company[0])
            return dict(company_default=company_default)
        return dict(company_default=None)

    @app.context_processor
    def messages_notifications():
        if current_user.is_authenticated:
            messages_notifications = PrivateMessages.query.filter(PrivateMessages.recipient_id == current_user.id).filter(PrivateMessages.read == False).order_by(PrivateMessages.create.desc()).all()
            return dict(messages_notifications=messages_notifications)
        return dict(messages_notifications=None)

    session_cookie = SecureCookieSessionInterface().get_signing_serializer(app)

    @app.after_request
    def cookies(response):
        same_cookie = session_cookie.dumps(dict(session))
        response.headers.add("Set-Cookie", f"my_cookie={same_cookie}; Secure; HttpOnly; SameSite=None; Path=/;")
        return response

    return app


from .models import *
from .model.equipment import *
from .model.menu import *
from .model.city import *
from .model.security import *

from .openweather import OpenWeather

weather = OpenWeather(appid=Config.APPID, db=db, model=Weather)


class AdminMixIn:
    def is_accessible(self):
        if current_user.is_anonymous:
            return False
        else:
            return 'admin' in current_user.roles

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class AdminView(AdminMixIn, ModelView):
    pass


class HomeAdminView(AdminMixIn, AdminIndexView):
    pass


admin.add_view(AdminView(Tour, db.session))
admin.add_view(AdminView(Event, db.session))
admin.add_view(AdminView(Artist, db.session))
admin.add_view(AdminView(Arena, db.session))
admin.add_view(AdminView(TypeHall, db.session))
admin.add_view(AdminView(TypeEvent, db.session))
admin.add_view(AdminView(Menu, db.session))

admin.add_view(AdminView(EquipmentCategory, db.session))
admin.add_view(AdminView(EquipmentSubcategory, db.session))
admin.add_view(AdminView(Equipment, db.session))

admin.add_view(AdminView(Country, db.session))
admin.add_view(AdminView(Region, db.session))
admin.add_view(AdminView(City, db.session))
admin.add_view(AdminView(Weather, db.session))

admin.add_view(AdminView(Document, db.session))
admin.add_view(AdminView(CompanyType, db.session))
admin.add_view(AdminView(Company, db.session))
admin.add_view(AdminView(RolesCompany, db.session))

admin.add_view(AdminView(User, db.session))
admin.add_view(AdminView(Role, db.session))
admin.add_view(AdminView(Confirmation, db.session))
admin.add_view(AdminView(Invite, db.session))
admin.add_view(AdminView(Settings, db.session))
admin.add_view(AdminView(PrivateMessages, db.session))


# user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)


def setup_logger():
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    formatter = logging.Formatter('%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    error_log = Config.LOG_DIR.joinpath('error.log')
    file_heandler = logging.FileHandler(error_log)

    file_heandler.setFormatter(formatter)
    logger.addHandler(file_heandler)

    return logger


logger = setup_logger()


def allowed_photo_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_PHOTO


def allowed_document_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_DOCUMENT


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


def generate_id():
    return str(uuid.uuid4())

event/equipment/views.py
from flask import Blueprint, jsonify
from blog import logger, session, docs
from blog.schemas import VideoSchema, UserSchema, AuthSchema, EquimentsSchema
from flask_apispec import use_kwargs, marshal_with
# from blog.models import Equipment, Event
from flask_jwt_extended import jwt_required, get_jwt_identity
from blog.base_view import BaseView

equipments = Blueprint('equipments', __name__)


@equipments.route('/catalog', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list():
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq
@equipments.route('/catalog/<int:light>', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list_light(light):
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.filter(Equipment.catalogeqs_id==light).all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq




@equipments.errorhandler(422)
def error_handler(err):
    headers = err.data.get('headers', None)
    messages = err.data.get('messages', ['Invalid request'])
    if headers:
        return jsonify({'message': messages}), 400, headers
    else:
        return jsonify({'message': messages}), 400


docs.register(get_list, blueprint='equipments')
# docs.register(update_list, blueprint='videos')
# docs.register(update_tutorial, blueprint='videos')
# docs.register(delete_list, blueprint='videos')
# docs.register(get_video, blueprint=videos)
# ListView.register(videos, docs, '/main', 'listview')

event/views/friends/__init__.py
# ----------------------------------------------------
# Program by Andrey Vestimy
#
#
# Version   Date    Info
# 1.0       2020    ----
#
# ----------------------------------------------------

event/views/friends/views.py
from flask import Blueprint, jsonify, request, json, render_template, redirect
from flask import abort
from event import logger, config, allowed_photo_profile
import os
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from flask_security import login_required, current_user
from event.decorators import decorated_admin
from event.forms import *

friends = Blueprint('friends', __name__)


@friends.route('/friends/', methods=['GET'])
@login_required
def index():
    return render_template('mailbox.html')

event/views/security/views.py
from flask import Blueprint, request, render_template, redirect, abort, session
from event import logger, config, allowed_photo_profile, allowed_document_profile, load_user
from event.emails import send_confirm, send_forgot, send_confirm_succes
from event import generate_id
from flask_login import logout_user, login_user, login_required, current_user
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from werkzeug.security import check_password_hash, generate_password_hash
from event.forms import *

from event.model.security import *

security = Blueprint('security', __name__)


@security.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('security.login'))


@security.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    login_user_form = LoginForm(request.form)
    email = request.form.get('email')
    password = request.form.get('password')
    if request.method == 'POST' and login_user_form.validate():
        if User.get_email(email):
            user = User.get_email(email)
        elif User.query.filter(User.login == email).first():
            user = User.query.filter(User.login == email).first()
        else:
            user = None
        if user.active:
            if user:
                if check_password_hash(user.password, password):
                    login_user(user)
                    session.permanent = True
                    next_page = request.args.get('next')
                    if next_page is None:
                        return redirect(url_for('main.index'))
                    return redirect(next_page)
                else:
                    flash('Неверый логин или пароль')
            else:
                flash('Пользователь не существует')
        else:
            flash('Пользователь не активирван')
    return render_template('security/login_user.html', login_user_form=login_user_form)


@security.route('/registration', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    role = Role.query.get(2)
    user = User()
    register_user_form = RegisterUserForm(request.form, obj=user)
    password = request.form.get('password')
    password_confirm = request.form.get('password_confirm')
    id = request.args.get('id')
    email = request.args.get('email')
    if id and email:
        register_user_form = RegisterInviteForm(request.form, obj=user)
        invite = Invite.query.filter(Invite.invite_id == id).first()
        if request.method == 'POST' and request.form.get(
                'submit_invite') and invite and invite.email == email:
            if register_user_form.validate():
                if not (login or password or password_confirm):
                    flash('Заполните все поля')
                elif password != password_confirm:
                    flash('Пароли не совпадают')
                else:
                    register_user_form.populate_obj(user)
                    hash_pwd = generate_password_hash(password)
                    user.password = hash_pwd
                    user.email = invite.email
                    user.active = True
                    user.roles.append(role)
                    db.session.add(user)

                    user.company.append(Company.query.get(invite.company_id))
                    settings = Settings(company_default_id=invite.company_id)
                    settings.users.append(user)
                    db.session.add(settings)
                    db.session.delete(invite)
                    db.session.commit()
                    # html = render_template('email_templates/action.html', user=user, id=id, password=password)
                    # send_confirm(user.email, html)
                return redirect(url_for('security.login'))
        return render_template('security/register_invite.html', register_user_form=register_user_form)
    if request.method == 'POST' and register_user_form.validate():
        if not (login or password or password_confirm):
            flash('Заполните все поля')
        elif password != password_confirm:
            flash('Пароли не совпадают')
        else:
            register_user_form.populate_obj(user)
            hash_pwd = generate_password_hash(password)
            user.password = hash_pwd
            user.roles.append(role)
            db.session.add(user)

            id = generate_id()
            confirmation = Confirmation(email=user.email, conf_id=id)
            db.session.add(confirmation)
            db.session.commit()

            html = render_template('email_templates/action.html', user=user, id=id, password=password)
            send_confirm(user.email, html)
        return redirect(url_for('security.login'))
    return render_template('security/register_user.html', register_user_form=register_user_form)


@security.route('/reset', methods=['GET', 'POST'])
def reset():
    form = ForgotPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.email == request.form.get('email')).first()
        html = render_template('email_templates/action.html', user=user)
        send_forgot(request.form.get('email'), html)
    return render_template('security/forgot_password.html', forgot_password_form=form)


@security.route('/confirmation', methods=['GET', 'POST'])
def confirmation():
    company = Company()
    form = CompanyForm(request.form, obj=company)
    email = request.args.get('email')
    id = request.args.get('id')
    if email and id:
        conf_id = Confirmation.query.filter(Confirmation.conf_id == id).first()
        if conf_id and conf_id.email == email:
            user = User.query.filter(User.email == conf_id.email).first()
            if request.method == 'POST':
                form.populate_obj(company)
                db.session.add(company)
                company.creator_id = user.id
                try:
                    company.staff.append(user)
                    company.user_admin.append(user)
                    db.session.commit()
                except Exception as e:
                    logger.warning(
                        f'Подвержение почты: {e}'
                    )
                if company:
                    db.session.delete(conf_id)
                    user.active = True
                    settings = Settings(company_default_id=company.id)
                    settings.users.append(user)
                    db.session.add(settings)
                    db.session.commit()
                html = render_template('email_templates/confirm_successful.html', user=user)
                send_confirm_succes(user.email, html)
                return redirect(url_for('security.login'))
            return render_template('security/confirmation.html', form=form)
    return abort(404)


@security.after_request
def redirect_to_signin(response):
    if response.status_code == 401:
        return redirect(url_for('security.login') + '?2next=' + request.url)
    return response

event/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
<!--{{ field.label }} -->
{% if field.errors %}
    {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endfor %}
{% endif %}
{{ field(**kwargs)|safe }}
{% endmacro %}

    {% macro render_field(field) %}

    {{ field(**kwargs)|safe }}
{% endmacro %}

event/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>{{ _('Menu') }}</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}

event/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-danger" role="alert">

    {{ message }}
    </div>
      
    {% endfor %}
  {% endif %}
{%- endwith %}

event/templates/security/change_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Change password') }}</h1>
<form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
  {{ change_password_form.hidden_tag() }}
  {{ render_field_with_errors(change_password_form.password) }}
  {{ render_field_with_errors(change_password_form.new_password) }}
  {{ render_field_with_errors(change_password_form.new_password_confirm) }}
  {{ render_field(change_password_form.submit) }}
</form>

event/templates/security/confirmation.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TM+ | Регистрация</title>
<link rel="shortcut icon" href="{{url_for('inspina', filename='favicon/favicon.ico')}}" type="image/x-icon">
    <link href="{{ url_for('inspina', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='font-awesome/css/font-awesome.css')}}" rel="stylesheet">

    <link href="{{ url_for('inspina', filename='css/animate.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='css/style.css')}}" rel="stylesheet">

    <link href="{{ url_for('inspina', filename='css/plugins/iCheck/custom.css')}}" rel="stylesheet">

    <style>
        .loginColumns{
            padding-top:10px;
        }
        .logo-name, h3, h4, h5, p{
            text-align: center;

        }



    </style>

</head>
<!--<div class="container aos-init aos-animate" data-aos="fade-up">-->


<body class="gray-bg">

<div class="loginColumns animated fadeInDown">
    <div class="row">
        <div class="col-md-12">
            <div>
                <div>
                    <h1 class="logo-name">TM+</h1>
                </div>
                <h3>Регистрация</h3>
                <p>Создайте учетную запись, чтобы увидеть это в действии.</p>
                <form class="m-t" role="form" action="" method="POST">

                    <div class="form-group">
                        {{ render_field_with_errors(form.companytype_id, type="text", class="form-control",
                        placeholder="Тип") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.name,type="text", class="form-control",
                        placeholder="Название", required="") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.email,class='form-control',type="email",
                        class="form-control", placeholder="Email", required="") }}
                    </div>


                    <div class="form-group">
                        {{ render_field_with_errors(form.phone, type="text", class="form-control",
                        placeholder="Телефон") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.city_id, type="text", class="form-control",
                        placeholder="Город") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.address, type="text", class="form-control",
                        placeholder="Адрес") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.instagram, type="text", class="form-control",
                        placeholder="Инстаграм") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.vk, type="text", class="form-control",
                        placeholder="VK") }}
                    </div>
                    <div class="form-group">
                        {{ render_field_with_errors(form.facebook, type="text", class="form-control",
                        placeholder="Facebook") }}
                    </div>


                    <div class="form-group">
                        <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Agree the terms and
                            policy
                        </label></div>
                    </div>
                    {{ render_field(form.submit, class="btn btn-primary block full-width m-b") }}

                    <p class="text-muted text-center"><small>Уже есть аккаунт?</small></p>
                    <a class="btn btn-sm btn-white btn-block" href="{{ url_for('security.login') }}">Войти</a>
                </form>
                <p class="m-t"><small>TM+ - touremanager.ru &copy; 2021</small></p>
            </div>
        </div>
    </div>
</div>
<!-- Mainly scripts -->
<script src="{{ url_for('inspina', filename='js/jquery-3.1.1.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/popper.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/bootstrap.js')}}"></script>
<!-- iCheck -->
<script src="{{ url_for('inspina', filename='js/plugins/iCheck/icheck.min.js')}}"></script>
<script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });











</script>
</body>

</html>

event/templates/security/forgot_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TM+ | Забыл пароль</title>

<link rel="shortcut icon" href="{{url_for('inspina', filename='favicon/favicon.ico')}}" type="image/x-icon">
    <link href="{{ url_for('inspina', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='font-awesome/css/font-awesome.css')}}" rel="stylesheet">

    <link href="{{ url_for('inspina', filename='css/animate.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='css/style.css')}}" rel="stylesheet">


</head>

<body class="gray-bg">

    <div class="passwordBox animated fadeInDown">
        <div class="row">

            <div class="col-md-12">
                <div class="ibox-content">

                    <h2 class="font-bold">Забыл пароль</h2>

                    <p>
                        Введите свой адрес электронной почты, и ваш пароль будет сброшен и отправлен Вам по электронной почте.
                    </p>

                    <div class="row">

                        <div class="col-lg-12">
                            <form class="m-t" role="form" action="" method="POST">
                                <div class="form-group">
                                    {{ render_field_with_errors(forgot_password_form.email, class="form-control", placeholder="Email address") }} 
                                </div>
  
  
                                {{ render_field(forgot_password_form.submit, class="btn btn-primary block full-width m-b") }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-12 text-center">
               <small>TM+ - touremanager.ru &copy; 2021</small>
            </div>
        </div>
    </div>

</body>

</html>

event/templates/security/login_user.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TM | Вход</title>
<link rel="shortcut icon" href="{{url_for('inspina', filename='favicon/favicon.ico')}}" type="image/x-icon">
    <link href="{{ url_for('inspina', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='font-awesome/css/font-awesome.css')}}" rel="stylesheet">

    <link href="{{ url_for('inspina', filename='css/animate.css')}}" rel="stylesheet">
    <link href="{{ url_for('inspina', filename='css/style.css')}}" rel="stylesheet">

</head>
<body class="gray-bg">
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <div>
            <h1 class="logo-name">TM+</h1>

        </div>
        <h3>Добро пожаловать.</h3>

        <p>Войдите в систему. <br>Чтобы увидеть это в действии.</p>
        {% from "security/_macros.html" import render_field_with_errors, render_field %}
        {% include "security/_messages.html" %}


        <form class="m-t" role="form" action="" method="POST" name="login_user_form"
        >


            {% if login_user_form.email.errors %}
            {% for error in login_user_form.email.errors %}

            {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ login_user_form.email(class='form-control', placeholder="email", required="")}}
            </div>
            <div class="form-group">
                {{ login_user_form.password(class='form-control', placeholder="password", required="") }}
            </div>
            {% if login_user_form.password.errors %}
            {% for error in login_user_form.password.errors %}
            <p class="alert-danger">{{ error }}</p>
            {% endfor %}
            {% endif %}

            <!--            {{ login_user_form.remember.label }}-->
            <!--            {{ login_user_form.remember }}-->


            {{ render_field(login_user_form.submit, class="btn btn-primary btn-lg btn-block") }}
            <a href="{{ url_for('security.reset') }}"><small>Забали пароль?</small></a>


            <p class="text-muted text-center"><small>Еще не регистрировались?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="{{ url_for('security.register') }}">Создать учётную
                запись</a>


        </form>
        <p class="m-t"><small>TM+ - touremanager.ru &copy; 2021</small></p>
    </div>
</div>
<!-- Mainly scripts -->
<script src="{{ url_for('inspina', filename='js/jquery-3.1.1.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/popper.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/bootstrap.js')}}"></script>

</body>

</html>

event/templates/security/login_user2.html
{% extends "base.html" %}
{% block content %}

    <div class="container aos-init aos-animate" data-aos="fade-up">
        <div class="row justify-content-evenly aos-init aos-animate">
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}

<!--<h1>{{ _('Login') }}</h1>-->
<form class="form-signin" action="{{ url_for_security('login') }}" method="POST" name="login_user_form" data-aos="fade-up">
<!--    <img class="mb-4" src="{{ url_for('static', filename='/assets/brand/bootstrap-solid.svg') }}" alt="" width="72" height="72">-->
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

    {{ login_user_form.hidden_tag() }}
    {{ render_field_with_errors(login_user_form.email, class='form-control') }}
    {{ render_field_with_errors(login_user_form.password, class='form-control') }}
    <div class="checkbox mb-3">
    <label>
    {{ render_field_with_errors(login_user_form.remember) }}
    </label>
  </div>
    {{ render_field(login_user_form.next) }}
    {{ render_field(login_user_form.submit, class="btn btn-lg btn-primary btn-block") }}
</form>
<!--{% include "security/_menu.html" %}-->
        </div>

    </div>

    <form class="login-form" action="index.html">
      <div class="login-wrap">
        <p class="login-img"><i class="icon_lock_alt"></i></p>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_profile"></i></span>
          <input type="text"  class="form-control" placeholder="Username" autofocus>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_key_alt"></i></span>
          <input type="password" class="form-control" placeholder="Password">
        </div>
        <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right"> <a href="#"> Forgot Password?</a></span>
            </label>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
        <button class="btn btn-info btn-lg btn-block" type="submit">Signup</button>
      </div>
    </form>{% endblock %}