event/__init__.py
import logging
import uuid
from flask import Flask, jsonify, flash, request, redirect, url_for, render_template, send_from_directory, json

from flask_sqlalchemy import SQLAlchemy
from .config import Config
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager
from flask_login import current_user, login_required
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from flask import session
from flask.sessions import SecureCookieSessionInterface

UPLOAD_FOLDER = '/home/vestimy/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

db = SQLAlchemy()
login_manager = LoginManager()
admin = Admin(name='admins')
# security = Security()
mail = Mail()
bootstrap = Bootstrap()

login_manager.login_view = 'security.login'
login_manager.login_message = u"Пожалуйста, авторизируйтесь."
from .forms_security import ExtendedRegisterForm


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    admin.init_app(app, url='/admin', index_view=HomeAdminView(name='Главная'))
    login_manager.init_app(app)
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
    mail.init_app(app)
    bootstrap.init_app(app)

    from .views.main.views import main
    from .views.event.views import events
    from .views.arena.views import arenas
    from .views.artist.views import artists
    from .views.manager.views import managers
    from .views.login.views import logins
    from .views.tour.views import tours
    from .views.api.views import api
    from .views.security.views import security
    from .views.profile.views import profiles
    from .views.message.views import messages
    from .views.friends.views import friends

    app.register_blueprint(main)
    app.register_blueprint(events)
    app.register_blueprint(arenas)
    app.register_blueprint(artists)
    app.register_blueprint(managers)
    app.register_blueprint(tours)
    app.register_blueprint(api)
    app.register_blueprint(security)
    app.register_blueprint(profiles)
    app.register_blueprint(messages)
    app.register_blueprint(friends)

    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    @app.route('/uploads/<filename>')
    def uploaded_file(filename):
        return send_from_directory(app.config['UPLOAD_PHOTO_PROFILES'],
                                   filename)

    @app.route('/photo_profile/<filename>')
    @login_required
    def photo_profile(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_PROFILES,
                                   filename)

    @app.route('/document_profile/<filename>')
    @login_required
    def document_profile(filename):
        return send_from_directory(Config.UPLOAD_DOCUMENTS_PROFILES,
                                   filename)

    @app.route('/img_arena/<img>')
    @login_required
    def img_arena(img):
        return send_from_directory(Config.UPLOAD_PHOTO_ARENA,
                                   img)

    @app.route('/photo_artist/<filename>')
    def photo_artist(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_ARTIST,
                                   filename)

    @app.route('/inspina/<path:filename>')
    def inspina(filename):
        return send_from_directory(Config.UPLOAD_ADMIN,
                                   filename)

    @app.context_processor
    def company_default():
        if current_user.is_authenticated:
            company_default = Company.query.get(current_user.settings.company_default_id)
            if not company_default:
                settings = Settings.query.get(current_user.settings_id)
                settings.company_default_id = current_user.company[0].id
                db.session.commit()
                company_default = Company.query.get(current_user.settings.company_default_id)
            # return dict(company_default=current_user.company[0])
            return dict(company_default=company_default)
        return dict(company_default=None)

    @app.context_processor
    def messages_notifications():
        if current_user.is_authenticated:
            messages_notifications = PrivateMessages.query.filter(PrivateMessages.recipient_id == current_user.id).filter(PrivateMessages.read == False).order_by(PrivateMessages.create.desc()).all()
            return dict(messages_notifications=messages_notifications)
        return dict(messages_notifications=None)

    session_cookie = SecureCookieSessionInterface().get_signing_serializer(app)

    @app.after_request
    def cookies(response):
        same_cookie = session_cookie.dumps(dict(session))
        response.headers.add("Set-Cookie", f"my_cookie={same_cookie}; Secure; HttpOnly; SameSite=None; Path=/;")
        return response

    return app


from .models import *
from .model.equipment import *
from .model.menu import *
from .model.city import *
from .model.security import *

from .openweather import OpenWeather

weather = OpenWeather(appid=Config.APPID, db=db, model=Weather)


class AdminMixIn:
    def is_accessible(self):
        if current_user.is_anonymous:
            return False
        else:
            return 'admin' in current_user.roles

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class AdminView(AdminMixIn, ModelView):
    pass


class HomeAdminView(AdminMixIn, AdminIndexView):
    pass


admin.add_view(AdminView(Tour, db.session))
admin.add_view(AdminView(Event, db.session))
admin.add_view(AdminView(Artist, db.session))
admin.add_view(AdminView(Arena, db.session))
admin.add_view(AdminView(TypeHall, db.session))
admin.add_view(AdminView(TypeEvent, db.session))
admin.add_view(AdminView(Menu, db.session))

admin.add_view(AdminView(EquipmentCategory, db.session))
admin.add_view(AdminView(EquipmentSubcategory, db.session))
admin.add_view(AdminView(Equipment, db.session))

admin.add_view(AdminView(Country, db.session))
admin.add_view(AdminView(Region, db.session))
admin.add_view(AdminView(City, db.session))
admin.add_view(AdminView(Weather, db.session))

admin.add_view(AdminView(Document, db.session))
admin.add_view(AdminView(CompanyType, db.session))
admin.add_view(AdminView(Company, db.session))
admin.add_view(AdminView(RolesCompany, db.session))

admin.add_view(AdminView(User, db.session))
admin.add_view(AdminView(Role, db.session))
admin.add_view(AdminView(Confirmation, db.session))
admin.add_view(AdminView(Invite, db.session))
admin.add_view(AdminView(Settings, db.session))
admin.add_view(AdminView(PrivateMessages, db.session))


# user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)


def setup_logger():
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    formatter = logging.Formatter('%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    error_log = Config.LOG_DIR.joinpath('error.log')
    file_heandler = logging.FileHandler(error_log)

    file_heandler.setFormatter(formatter)
    logger.addHandler(file_heandler)

    return logger


logger = setup_logger()


def allowed_photo_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_PHOTO


def allowed_document_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_DOCUMENT


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


def generate_id():
    return str(uuid.uuid4())

event/equipment/views.py
from flask import Blueprint, jsonify
from blog import logger, session, docs
from blog.schemas import VideoSchema, UserSchema, AuthSchema, EquimentsSchema
from flask_apispec import use_kwargs, marshal_with
# from blog.models import Equipment, Event
from flask_jwt_extended import jwt_required, get_jwt_identity
from blog.base_view import BaseView

equipments = Blueprint('equipments', __name__)


@equipments.route('/catalog', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list():
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq
@equipments.route('/catalog/<int:light>', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list_light(light):
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.filter(Equipment.catalogeqs_id==light).all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq




@equipments.errorhandler(422)
def error_handler(err):
    headers = err.data.get('headers', None)
    messages = err.data.get('messages', ['Invalid request'])
    if headers:
        return jsonify({'message': messages}), 400, headers
    else:
        return jsonify({'message': messages}), 400


docs.register(get_list, blueprint='equipments')
# docs.register(update_list, blueprint='videos')
# docs.register(update_tutorial, blueprint='videos')
# docs.register(delete_list, blueprint='videos')
# docs.register(get_video, blueprint=videos)
# ListView.register(videos, docs, '/main', 'listview')

event/login/views.py
from flask import Blueprint, render_template, redirect, flash
from flask_jwt_extended import jwt_required, get_jwt_identity
from blog.base_view import BaseView
from flask_apispec import use_kwargs, marshal_with
from blog import logger, docs, session
from blog.schemas import UserSchema, AuthSchema
from blog.models import Admin, User
from blog.forms import LoginForm, ContactForm

logins = Blueprint('logins', __name__)


@logins.route('/login', methods=['GET', 'POST'])
def login():
    # Here we use a class of some kind to represent and validate our
    # client-side form data. For example, WTForms is a library that will
    # handle this for us, and we use a custom LoginForm to validate.
    form = LoginForm()
    if form.validate_on_submit():
        # Login and validate the user.
        # user should be an instance of your `User` class
        login_user(user)

        flash('Logged in successfully.')

        next = request.args.get('next')
        # is_safe_url should check if the url is safe for redirects.
        # See http://flask.pocoo.org/snippets/62/ for an example.
        if not is_safe_url(next):
            return flask.abort(400)

        return redirect(next or flask.url_for('index'))
    return render_template('login.html', form=form)


# AdminAuthView.register(admin, docs, '/admin', 'adminauthview')
# AdminUsersView.register(admin, docs, '/admin', 'adminuserview')

event/views/arena/views.py
import os
from flask import Blueprint, jsonify, request, render_template, redirect, abort
from event import logger, config, allowed_photo_profile
from flask_security import login_required, roles_required, current_user, login_user
from flask import flash, request, redirect, url_for
from event.forms import *
from werkzeug.utils import secure_filename
from event.decorators import admin_required

arenas = Blueprint('arenas', __name__)


@arenas.route('/arena', methods=['GET'])
@login_required
def index():
    id = None
    citys = None
    if request.args.get('q'):
        arena = Arena.query.join(City).filter(
            City.name.contains(request.args.get('q')) | Arena.name.contains(
                request.args.get('q')) | Arena.alias.contains(request.args.get('q'))).all()
    else:
        arena = Arena.query.order_by('name').all()
        if request.args.get('type'):
            try:
                id = int(request.args.get('type'))
            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(id, int):
                arena = Arena.query.filter(
                    Arena.typehall_id == id).order_by('name').all()
        if request.args.get('city'):
            try:
                city = int(request.args.get('city'))

            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(city, int):
                arena = Arena.query.filter(
                    Arena.city_id == city).order_by('name').all()
                city_query = City.query.filter(City.id == city).one()
                citys = city_query.name
        if request.args.get('region'):
            try:
                region = int(request.args.get('region'))

            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(region, int):
                arena = Arena.query.join(City).filter(City.region_id == region)

    typehall = TypeHall.query.order_by('name').all()
    return render_template('arena.html', menu='arenas', id=id, typehall=typehall, arena=arena, citys=citys)


@arenas.route('/arena/<int:id>', methods=['GET', 'POST'])
@login_required
def arena_detail(id):
    try:
        arena = Arena.query.get(id)
        if not arena:
            return redirect(request.root)
        if request.method == 'POST':
            file = request.files['file']
            print(file)
    except Exception as e:
        logger.warning(
            f"{current_user.last_name} - Ошибка при загрузке одной площадки: {e}"
        )
        return redirect(url_for('main.index'))
    return render_template('arena_detail.html', menu='arenas', arena=arena)


@arenas.route('/test/', methods=['GET', 'POST'])
@login_required
def test():
    form = TestForm()
    return render_template('test.html', form=form)


@arenas.route('/arena/add', methods=['GET', 'POST'])
@login_required
def add():
    arena = Arena()
    form = ArenaForm(request.form, obj=arena)
    if request.method == 'POST' and form.validate():
        if request.files['img']:
            file = request.files['img']
            if file.filename == '':
                flash('No selected file')
                return redirect(request.url)
            try:
                if file and allowed_photo_profile(file.filename):
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(
                        config.Config.UPLOAD_PHOTO_ARENA, filename))
                    form.populate_obj(arena)
                    db.session.add(arena)
                    db.session.commit()
                    arena.img = filename
                    db.session.commit()
                    return redirect(url_for('arenas.arena_detail', id=arena.id))
            except Exception as e:
                logger.warning(
                    f"{filename}-Ошибка файла: {e}"
                )
                abort(404)
        form.populate_obj(arena)
        try:
            db.session.add(arena)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.warning(
                f'{current_user.id}-{current_user.last_name} - Ошибка при добавлении площадки: {e}'
            )

        return redirect(url_for('arenas.arena_detail', id=arena.id))

    return render_template('add_arena.html', menu='arenas', form=form)


@arenas.route('/arena/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    arena = Arena.query.get(id)
    form = ArenaForm(request.form, obj=arena)
    if arena.city_id:
        form.city_id.choices = [(arena.city.id, arena.city.name)]
    if request.method == 'POST':
        # if request.files['img']:
        #     file = request.files['img']
        #     if file.filename == '':
        #         flash('No selected file')
        #         return redirect(request.url)
        #     try:
        #         if file and allowed_photo_profile(file.filename):
        #             filename = secure_filename(file.filename)
        #             file.save(os.path.join(config.Config.UPLOAD_PHOTO_ARENA, filename))
        #     except Exception as e:
        #         logger.warning(
        #             f"{filename}-Ошибка файла: {e}"
        #         )
        #         return 404
        if arena.name == request.form['name']:
            form.populate_obj(arena)
            # if request.files['img']:
            #     arena.img = filename
            db.session.commit()
            return redirect(url_for('arenas.arena_detail', id=arena.id))
        if form.validate():
            form.populate_obj(arena)
            # if request.files['img']:
            #     arena.img = filename
            db.session.commit()
            return redirect(url_for('arenas.arena_detail', id=arena.id))

    # form.city_id.choices = [(g.id, g.name) for g in City.query.order_by('name')]
    return render_template('arena_edit.html', menu='arenas', arena=arena, form=form)


@arenas.route('/arena/delete/<int:id>', methods=['GET'])
@login_required
def delete_arena(id):
    arena = Arena.query.get(id)
    db.session.delete(arena)
    db.session.commit()
    return redirect(url_for('arenas.get_list_arena'))


@arenas.errorhandler(422)
def error_handler(err):
    headers = err.data.get('headers', None)
    messages = err.data.get('messages', ['Invalid request'])
    if headers:
        return jsonify({'message': messages}), 400, headers
    else:
        return jsonify({'message': messages}), 400

event/views/friends/__init__.py
# ----------------------------------------------------
# Program by Andrey Vestimy
#
#
# Version   Date    Info
# 1.0       2020    ----
#
# ----------------------------------------------------

event/templates/arena.html
{% extends "base/base.html" %}
{% block title %}
<title>Площадки | TM+</title>

{% endblock %}


{% block head_style %}
<link href="{{ url_for('inspina', filename='css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css')}}"
      rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
{% endblock %}


{% block content %}

<div class="row">
    <div class="col-lg-12 animated fadeInUp">
        <div class="ibox">
            <div class="ibox-title">
                {% if citys %}
                <h5>Площадки в городе {{ citys }}</h5>
                {% else %}
                <h5>Площадки</h5>
                {% endif %}
                <div class="ibox-tools">
                    <a href="{{ url_for('arenas.add') }}" class="btn btn-primary btn-xs">Добавить</a>
                </div>
                <div class="col-md-12">

                    <form method="GET">
                        <div class="input-group">
                            <input name="q" type="text" placeholder="Поиск по городу или названию"
                                   class="form-control-sm form-control" value="{{ request.args.get('q','') }}">
                            <span class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-primary"> Go!</button>
                                    </span>

                        </div>
                    </form>
                </div>
                <div class="col-md-12">

                    <div class="ibox-content">
                        {% for type in typehall %}
                        <span class="input-group-btn">
                                    <a href="{{ url_for('arenas.index', type=type.id)}}"><button type="submit"
                                                                                                 class="btn btn-sm btn-primary"> {{type.name}}</button></a>
                                </span>

                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="ibox-content">

                <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                    <thead>
                    <tr>

                        <th data-toggle="true">Название</th>
                        <th data-hide="phone">Город</th>
                        <th data-hide="all">Описание</th>
                        <!--                        <th data-hide="phone">Количество мест</th>-->
                        <!--                        <th data-hide="phone,tablet">Quantity</th>-->
                        <!--                        <th data-hide="phone">Status</th>-->
                        <th class="text-right" data-sort-ignore="true">Action</th>

                    </tr>
                    </thead>
                    <tbody>

                    {% for i in arena %}
                    <tr>
                        <td class="project-title">
                            <a href="{{url_for('arenas.arena_detail', id=i.id)}}">{{ i.name }} {% if i.alias %}
                                ({{i.alias}}){%endif%}</a>
                            <br/>
                            {% if i.typehall %}
                            <a href="{{ url_for('arenas.index', type=i.typehall.id) }}"><small>{{ i.typehall
                                }}</small></a>
                            {% endif %}
                        </td>
                        <td class="project-completion">
                            {% if i.city %}
                            <a href="{{ url_for('arenas.index',  q=i.city) }}"> <small>{{i.city}}</small></a>
                            {% endif %}
                        </td>
                        <td>
                            {{ i.description }}
                        </td>
                        <!--                        <td>-->
                        <!--                            {{ i.number_of_seats }}-->
                        <!--                        </td>-->
                        <!--                        <td>-->
                        <!--                            1000-->
                        <!--                        </td>-->
                        <!--                        <td>-->
                        <!--                            <span class="label label-primary">Enable</span>-->
                        <!--                        </td>-->
                        <td class="text-right">
                            <div class="btn-group">
                                <a href="{{url_for('arenas.arena_detail', id=i.id)}}">
                                    <button class="btn-white btn btn-xs"> Посмотреть</button>
                                </a>
                                <a href="{{ url_for('arenas.edit', id=i.id) }}">
                                    <button class="btn-white btn btn-xs">Редактировать</button>
                                </a>

                            </div>
                        </td>
                    </tr>
                    {% endfor %}


                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="6">
                            <ul class="pagination float-right"></ul>
                        </td>
                    </tr>
                    </tfoot>
                </table>

            </div>
        </div>
    </div>
</div>

{% endblock %}
<!-- Mainly scripts -->
{% block script %}
<!-- FooTable -->
<script src="{{ url_for('inspina', filename='js/plugins/footable/footable.all.min.js')}}"></script>

<!-- Page-Level Scripts -->
<script>
        $(document).ready(function() {

            $('.footable').footable();

        });



</script>
{% endblock %}

event/templates/login_two_columns.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Login 2</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="loginColumns animated fadeInDown">
        <div class="row">

            <div class="col-md-6">
                <h2 class="font-bold">Welcome to IN+</h2>

                <p>
                    Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
                </p>

                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                </p>

                <p>
                    When an unknown printer took a galley of type and scrambled it to make a type specimen book.
                </p>

                <p>
                    <small>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</small>
                </p>

            </div>
            <div class="col-md-6">
                <div class="ibox-content">
                    <form class="m-t" role="form" action="index.html">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Username" required="">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password" required="">
                        </div>
                        <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                        <a href="#">
                            <small>Forgot password?</small>
                        </a>

                        <p class="text-muted text-center">
                            <small>Do not have an account?</small>
                        </p>
                        <a class="btn btn-sm btn-white btn-block" href="register.html">Create an account</a>
                    </form>
                    <p class="m-t">
                        <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small>
                    </p>
                </div>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-6">
                Copyright Example Company
            </div>
            <div class="col-md-6 text-right">
               <small>© 2014-2015</small>
            </div>
        </div>
    </div>

</body>

</html>