event/views/arena/views.py
import os
from flask import Blueprint, jsonify, request, render_template, redirect, abort
from event import logger, config, allowed_photo_profile
from flask_security import login_required, roles_required, current_user, login_user
from flask import flash, request, redirect, url_for
from event.forms import *
from werkzeug.utils import secure_filename
from event.decorators import admin_required

arenas = Blueprint('arenas', __name__)


@arenas.route('/arena', methods=['GET'])
@login_required
def index():
    id = None
    citys = None
    if request.args.get('q'):
        arena = Arena.query.join(City).filter(
            City.name.contains(request.args.get('q')) | Arena.name.contains(
                request.args.get('q')) | Arena.alias.contains(request.args.get('q'))).all()
    else:
        arena = Arena.query.order_by('name').all()
        if request.args.get('type'):
            try:
                id = int(request.args.get('type'))
            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(id, int):
                arena = Arena.query.filter(
                    Arena.typehall_id == id).order_by('name').all()
        if request.args.get('city'):
            try:
                city = int(request.args.get('city'))

            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(city, int):
                arena = Arena.query.filter(
                    Arena.city_id == city).order_by('name').all()
                city_query = City.query.filter(City.id == city).one()
                citys = city_query.name
        if request.args.get('region'):
            try:
                region = int(request.args.get('region'))

            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
            if isinstance(region, int):
                arena = Arena.query.join(City).filter(City.region_id == region)

    typehall = TypeHall.query.order_by('name').all()
    return render_template('arena.html', menu='arenas', id=id, typehall=typehall, arena=arena, citys=citys)


@arenas.route('/arena/<int:id>', methods=['GET', 'POST'])
@login_required
def arena_detail(id):
    try:
        arena = Arena.query.get(id)
        if not arena:
            return redirect(request.root)
        if request.method == 'POST':
            file = request.files['file']
            print(file)
    except Exception as e:
        logger.warning(
            f"{current_user.last_name} - Ошибка при загрузке одной площадки: {e}"
        )
        return redirect(url_for('main.index'))
    return render_template('arena_detail.html', menu='arenas', arena=arena)


@arenas.route('/test/', methods=['GET', 'POST'])
@login_required
def test():
    form = TestForm()
    return render_template('test.html', form=form)


@arenas.route('/arena/add', methods=['GET', 'POST'])
@login_required
def add():
    arena = Arena()
    form = ArenaForm(request.form, obj=arena)
    if request.method == 'POST' and form.validate():
        if request.files['img']:
            file = request.files['img']
            if file.filename == '':
                flash('No selected file')
                return redirect(request.url)
            try:
                if file and allowed_photo_profile(file.filename):
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(
                        config.Config.UPLOAD_PHOTO_ARENA, filename))
                    form.populate_obj(arena)
                    db.session.add(arena)
                    db.session.commit()
                    arena.img = filename
                    db.session.commit()
                    return redirect(url_for('arenas.arena_detail', id=arena.id))
            except Exception as e:
                logger.warning(
                    f"{filename}-Ошибка файла: {e}"
                )
                abort(404)
        form.populate_obj(arena)
        try:
            db.session.add(arena)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            logger.warning(
                f'{current_user.id}-{current_user.last_name} - Ошибка при добавлении площадки: {e}'
            )

        return redirect(url_for('arenas.arena_detail', id=arena.id))

    return render_template('add_arena.html', menu='arenas', form=form)


@arenas.route('/arena/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    arena = Arena.query.get(id)
    form = ArenaForm(request.form, obj=arena)
    if arena.city_id:
        form.city_id.choices = [(arena.city.id, arena.city.name)]
    if request.method == 'POST':
        # if request.files['img']:
        #     file = request.files['img']
        #     if file.filename == '':
        #         flash('No selected file')
        #         return redirect(request.url)
        #     try:
        #         if file and allowed_photo_profile(file.filename):
        #             filename = secure_filename(file.filename)
        #             file.save(os.path.join(config.Config.UPLOAD_PHOTO_ARENA, filename))
        #     except Exception as e:
        #         logger.warning(
        #             f"{filename}-Ошибка файла: {e}"
        #         )
        #         return 404
        if arena.name == request.form['name']:
            form.populate_obj(arena)
            # if request.files['img']:
            #     arena.img = filename
            db.session.commit()
            return redirect(url_for('arenas.arena_detail', id=arena.id))
        if form.validate():
            form.populate_obj(arena)
            # if request.files['img']:
            #     arena.img = filename
            db.session.commit()
            return redirect(url_for('arenas.arena_detail', id=arena.id))

    # form.city_id.choices = [(g.id, g.name) for g in City.query.order_by('name')]
    return render_template('arena_edit.html', menu='arenas', arena=arena, form=form)


@arenas.route('/arena/delete/<int:id>', methods=['GET'])
@login_required
def delete_arena(id):
    arena = Arena.query.get(id)
    db.session.delete(arena)
    db.session.commit()
    return redirect(url_for('arenas.get_list_arena'))


@arenas.errorhandler(422)
def error_handler(err):
    headers = err.data.get('headers', None)
    messages = err.data.get('messages', ['Invalid request'])
    if headers:
        return jsonify({'message': messages}), 400, headers
    else:
        return jsonify({'message': messages}), 400

event/views/event/views.py
from flask import Blueprint, jsonify, request, abort, json, render_template
from event import logger, config, weather
from werkzeug.utils import secure_filename
from event import logger, config
from event.models import *
from event.model.city import *
import os
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from flask_mail import Message
from flask_security import login_required, current_user, roles_required, roles_accepted
from event.forms import *
from datetime import datetime
events = Blueprint('events', __name__)

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

UPLOAD_FOLDER = 'uploads'


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@events.route('/event', methods=['GET'])
@login_required
def index():
    company_id = current_user.settings.company_default_id
    type_event = TypeEvent.query.order_by('name').all()
    id = None
    if request.args.get('q'):
        event = Event.query.join(Arena).join(City).join(Artist).filter(Event.company_id == company_id).filter(
            Arena.name.contains(
                request.args.get('q')) | Event.date_event.contains(
                request.args.get('q')) | Event.time_event.contains(
                request.args.get('q')) | Arena.alias.contains(
                request.args.get('q')) | Artist.last_name.contains(
                request.args.get('q')) | Artist.alias.contains(
                request.args.get('q')) | Artist.first_name.contains(
                request.args.get('q')) | City.name.contains(
                request.args.get('q'))).all()
    else:

        if request.args.get('id'):
            event = Event.query.get_or_404(request.args.get('id'))
            return render_template('event.html', id=id, menu='events', events=event, type_event=type_event)
        try:
            event = Event.query.filter(Event.company_id == company_id).filter(Event.date_event >= datetime.now().date()).order_by(Event.date_event.desc())
            if request.args.get('all'):
                try:
                    id = str(request.args.get('all'))
                except Exception as e:
                    logger.warning(
                        f'arenas -  action failed with errors: {e}'
                    )
                if isinstance(id, str):
                    event = Event.query.filter(Event.company_id == company_id).order_by(Event.date_event.desc())
            if request.args.get('type'):
                try:
                    id = int(request.args.get('type'))
                except Exception as e:
                    logger.warning(
                        f'arenas -  action failed with errors: {e}'
                    )
                if isinstance(id, int):
                    event = Event.query.filter(Event.company_id == company_id).filter(Event.typeevent_id == id).order_by(
                        Event.date_event.desc()).all()

        except Exception as e:
            logger.warning(
                f'user: {current_user.last_name} Events - read action failed with errors: {e}'
            )
            return {'message': str(e)}, 400
        if request.args.get('id'):
            try:
                id = int(request.args.get('id'))
            except Exception as e:
                logger.warning(
                    f'arenas -  action failed with errors: {e}'
                )
                return redirect(request.url)
            if isinstance(id, int):
                event = Event.query.filter(Event.typeevent_id == id).order_by(
                    Event.date_event.desc()).all()
    return render_template('event.html', id=id, menu='events', events=event, type_event=type_event)


@events.route('/event/<int:id>', methods=['GET'])
@login_required
def detail(id):
    data = None
    event = Event.query.get_or_404(id)
    arena = Arena.query.get(event.arena_id)
    if event.city:
        name = event.city.name
        if '(' in name:
            name = name.split('(')[0].strip()
        try:
            data = weather.get(q=name)
        except Exception:
            pass
            data = None
    return render_template('event_detail.html', menu='events', event=event, weathers=data, arena=arena)


@events.route('/add_event/', methods=['GET', 'POST'])
@login_required
# @roles_accepted('admin ', 'manager')
def add():
    default_id = current_user.settings.company_default_id
    event = Event()
    form = EventForm(request.form, obj=event)
    if request.method == "POST":
        try:
            form.populate_obj(event)
            db.session.add(event)
            event.company_id = default_id
            db.session.commit()
            if request.form.getlist('users_staffs'):
                for i in request.form.getlist('users_staffs'):
                    event.users_staff.append(User.query.get(i))
                db.session.commit()
        except Exception as e:
            print(e)
            logger.warning(
                f'Ошибка при добавлении мерроприятия: {e}'
            )
            db.session.rollback()

    form.users_staffs.choices = [(g.id, g) for g in
                                 User.query.filter(
                                     User.company.any(
                                         Company.id.in_(
                                             [current_user.settings.company_default_id]
                                         )
                                     )
                                 )
                                 ]
    return render_template('event_add.html', menu='events', form=form)


@events.route('/events/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    event = Event.query.filter(Event.id == id).first()
    form = EventForm(obj=event)
    print(current_user.id)
    print(event.user_id)
    if current_user.id == event.user_id or "admin" in current_user.roles:
        # print(form.date_event)
        if event is None:
            raise Exception('Ошибка нет такого поста')
        if request.method == 'POST':
            form = EventForm(formdata=request.form, obj=event)
            print(form.time_event)
            form.populate_obj(event)
            db.session.commit()

            return redirect(url_for('events.get_item_event', menu='events', id=event.id))

        # form.artist_id.choices = [(g.id, g.name) for g in Artist.query.order_by('name')]
        # form.city_id.choices = [(g.id, g.name) for g in City.query.order_by('name')]
        # form.arena_id.choices = [(g.id, g.name) for g in Arena.query.order_by('name')]
        # form.manager_id.choices = [(g.id, g.name) for g in Manager.query.order_by('name')]

        return render_template('event/edit_event.html', menu='events', form=form, item=event)
    return redirect(url_for("events.get_event"))


@events.route('/events/delete/<int:id>', methods=['GET'])
@login_required
def delete(id):
    event = Event.query.get(id)
    if current_user.id == event.user_id or "admin" in current_user.roles:
        db.session.delete(event)
        db.session.commit()
        return redirect(url_for('events.get_event'))


@events.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_file():
    if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            item = Rider(name=filename, url=filename)
            session.add(item)
            session.commit()
            file.save(os.path.join(
                '/home/vestimy/video_blog/blog/uploads', filename))
            return redirect(url_for('uploaded_file',
                                    filename=filename))

    else:
        return render_template('upload.html', menu='events')

event/views/friends/__init__.py
# ----------------------------------------------------
# Program by Andrey Vestimy
#
#
# Version   Date    Info
# 1.0       2020    ----
#
# ----------------------------------------------------

event/views/friends/views.py
from flask import Blueprint, jsonify, request, json, render_template, redirect
from flask import abort
from event import logger, config, allowed_photo_profile
import os
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from flask_security import login_required, current_user
from event.decorators import decorated_admin
from event.forms import *

friends = Blueprint('friends', __name__)


@friends.route('/friends/', methods=['GET'])
@login_required
def index():
    return render_template('mailbox.html')

event/views/message/views.py
from flask import Blueprint, jsonify, request, json, render_template, redirect
from flask import abort
from event import logger, config, allowed_photo_profile
import os
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from flask_security import login_required, current_user
from event.decorators import decorated_admin
from event.forms import *

messages = Blueprint('messages', __name__)


@messages.route('/messages/', methods=['GET'])
@login_required
def index():
    messages = PrivateMessages.query.filter(PrivateMessages.recipient_id == current_user.id).order_by(
        PrivateMessages.create.desc()).all()
    return render_template('mailbox.html', messages=messages)


@messages.route('/api/send_message/<int:id>', methods=['GET', 'POST'])
@login_required
def send_message(id):
    sender = User.query.get(current_user.id)
    recipient = User.query.get(id)
    message = PrivateMessages()
    form = SendMessageForm(request.form, message)
    if request.method == 'POST':
        try:
            form.populate_obj(message)
            message.sender_id = sender.id
            message.recipient_id = recipient.id
            message.read = False
            db.session.add(message)
            db.session.commit()
        except Exception as e:
            print(f'error {e}')
            db.session.rollback()
    return redirect(request.referrer)

event/templates/base/base.html
<!DOCTYPE html>
<html>

<head>
    {% block title %}
    {% endblock %}
    {% include "base/style.html" %}
    {% block head_style %}
    {% endblock %}
</head>

<body class="">
<div id="wrapper">
    {% include "base/nav.html" %}

    {% block menu %}
    {% endblock %}
    <div id="page-wrapper" class="gray-bg">
        {% include 'base/nav_top.html' %}
        <!--        {% if menu != "index" %}-->
        <!--        {% include 'base/bread.html' %}-->
        <!--        {% endif %}-->
        {% block content %}

        {% endblock %}
        {% include 'base/footer.html' %}
    </div>
    {% include 'base/dop_menu.html' %}
</div>

{% include "base/script.html" %}
{% block script %}

{% endblock %}
</body>
</html>

event/templates/base/bread.html
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-9">
                <h2>Contacts</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        App Views
                    </li>
                    <li class="breadcrumb-item active">
                        <strong>Contacts</strong>
                    </li>
                </ol>
            </div>
        </div>

event/templates/base/footer.html
<div class="footer">
    <div class="float-right">
        <a href="https://www.facebook.com/vestimyandrey/" ><strong>Vestimy Andrey</strong></a>
    </div>
    <div>
        <strong>Copyright</strong> TM+ Company &copy; 2020
    </div>
</div>

event/templates/base/nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    {% if current_user.photo %}
                    <img alt="image" class="rounded-circle my-style"
                         src="{{ url_for('photo_profile', filename=current_user.photo )}}"/>
                    {% else %}
                    <img alt="image" class="rounded-circle "
                         src="{{ url_for('photo_profile', filename='profile-default.jpeg') }}"
                         style="max-width: 48px;"/>
                    {% endif %}
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">{% if current_user.first_name %}{{ current_user.last_name }} {{ current_user.first_name }}{% else %}{{ current_user.login }} {% endif %}</span>
                        <span class="text-muted text-xs block">{{ current_user.roles[0].title }} <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a class="dropdown-item"
                               href="{{ url_for('profiles.profile', id=current_user.id) }}">Профиль</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('friends.index') }}">Друзья</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('messages.index') }}">Сообщения</a></li>
                        <li class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{{ url_for('security.logout')}}">Выйти</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    TM+
                </div>
            </li>
            {% if current_user.company|length > 1 %}
            <li class="special_link">
                <a href="{{url_for('main.index')}}"><i class="fa fa-building"></i> <span class="nav-label">{{ company_default.name}}</span>
                </a>
                <ul class="nav nav-second-level collapse">
                    {% for i in current_user.company %}
                    <li><a href="{{ url_for('main.default_company', id=i.id)}}">{{ i.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            {% endif %}
            <li {% if menu==
            'index' %} class='active' {% endif %}>
            <a href="{{url_for('main.index')}}"><i class="fa fa-home"></i> <span class="nav-label">Главная</span> </a>

            </li>
            <li {% if menu==
            'events' %} class='active' {% endif %}>
            <a href="{{url_for('events.index')}}"><i class="fa fa-calendar-o"></i> <span
                    class="nav-label">Мероприятия</span> </a>

            </li>
            <li {% if url_for('messages.index') == request.path %} class='active' {% endif %}>
            <a href="{{url_for('messages.index')}}"><i class="fa fa-commenting"></i> <span
                    class="nav-label">Сообщения</span> </a>

            </li>
            <li {% if menu==
            "artists" %} class="active" {% endif %}>
            <a href="{{ url_for('artists.index') }}"><i class="fa fa-star"></i> <span class="nav-label">Артисты</span>
            </a>

            </li>
            <li {% if menu==
            "arenas" %} class="active" {% endif %}>
            <a href="{{ url_for('arenas.index') }}"><i class="fa fa-address-card"></i> <span
                    class="nav-label">Площадки</span> <span class="float-right label label-primary">SPECIAL</span> </a>

            </li>

            <li {% if url_for(
            'profiles.team') == request.path %} class="active" {% endif %}>
            <a href="{{ url_for('profiles.team') }}"><i class="fa fa-users"></i> <span
                    class="nav-label">Сотрудники</span></a>
            </li>
            {% if current_user.creator or current_user in company_default.admins %}
            <li {% if url_for(
            'main.invite') == request.path %} class="active" {% endif %}>
            <a href="{{ url_for('main.invite') }}"><i class="fa fa-share"></i> <span
                    class="nav-label">Пригласить</span></a>
            </li>
            {% endif %}
            {% if 'super_admin' in current_user.roles %}
            <li class="special_link">
                <a href="{{ url_for('admin.index') }}"><i class="fa fa-database"></i> <span
                        class="nav-label">Админка</span></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

event/templates/base/nav_top.html
<div class="row border-bottom" xmlns="http://www.w3.org/1999/html">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i>
            </a>
            <!--            <form role="search" class="navbar-form-custom" action="search_results.html">-->
            <!--                <div class="form-group">-->
            <!--                    <input type="text" placeholder="Search for something..." class="form-control"-->
            <!--                           name="top-search" id="top-search">-->
            <!--                </div>-->
            <!--            </form>-->
            <ul class="nav navbar-top-links">
                <li class="dropdown" style="padding-left: 20px; ">
                    <a class="dropdown-toggle " data-toggle="dropdown" href="#">
                        <span class="label label-warning" style="font-size: 18px;">{{ company_default.name}}</span>
                    </a>


                </li>
            </ul>

        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li style="padding: 20px">
                <span class="m-r-sm text-muted welcome-message">Добро пожаловать {% if current_user.first_name %}{{current_user.first_name}} {% else %} {{ current_user.login }} {% endif %}.</span>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope"></i> <span class="label label-warning">{{ messages_notifications | length }}</span>
                </a>
                <ul class="dropdown-menu dropdown-messages dropdown-menu-right" style="left: 0;">
                    {% for i in messages_notifications %}
                    <li>
                        <div class="dropdown-messages-box">
                            <a class="dropdown-item float-left" href="{{ url_for('profiles.profile', id=i.sender.id)}}">
                                {% if i.sender.photo %}

                                <img alt="image" class="rounded-circle"
                                     src="{{ url_for('photo_profile', filename=i.sender.photo)}}">
                                {% else %}
                                <img alt="image" class="rounded-circle"
                                     src="{{ url_for('inspina', filename='img/a7.jpg')}}">
                                {% endif %}
                            </a>
                            <div class="media-body">
                                <a href="#" class="dropdown-item float-left">
                                    <!--                                <small class="float-right">46h ago</small>-->
                                    <strong>{{ i.sender.last_name }} {{ i.sender.first_name }}</strong> <br>Тема:
                                    <strong>{{
                                        i.subject }}</strong>.
                                    <br>
                                    <small class="text-muted">{{ i.create }}</small>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown-divider"></li>
                    {% endfor %}


                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell"></i> <span class="label label-primary">8</span>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="mailbox.html" class="dropdown-item">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="profile.html" class="dropdown-item">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="float-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <a href="grid_options.html" class="dropdown-item">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="float-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="dropdown-divider"></li>
                    <li>
                        <div class="text-center link-block">
                            <a href="notifications.html" class="dropdown-item">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>


            <li>
                <a href="{{ url_for('security.logout')}}">
                    <i class="fa fa-sign-out"></i> Выйти
                </a>
            </li>
            <li>
                <a class="right-sidebar-toggle">
                    <i class="fa fa-tasks"></i>
                </a>
            </li>
        </ul>

    </nav>
</div>

event/templates/base/script.html
<!-- Mainly scripts -->
<script src="{{ url_for('inspina', filename='js/jquery-3.1.1.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/popper.min.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/bootstrap.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/plugins/metisMenu/jquery.metisMenu.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/plugins/slimscroll/jquery.slimscroll.min.js')}}"></script>


<!-- Custom and plugin javascript -->
<script src="{{ url_for('inspina', filename='js/inspinia.js')}}"></script>
<script src="{{ url_for('inspina', filename='js/plugins/pace/pace.min.js')}}"></script>

<script src="{{ url_for('inspina', filename='js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>

event/templates/base/script_user.html
<script>
    $(document).ready(function() {

});
</script>