event/__init__.py
import logging
import uuid
from flask import Flask, jsonify, flash, request, redirect, url_for, render_template, send_from_directory, json

from flask_sqlalchemy import SQLAlchemy
from .config import Config
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager
from flask_login import current_user, login_required
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from flask import session
from flask.sessions import SecureCookieSessionInterface

UPLOAD_FOLDER = '/home/vestimy/uploads'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

db = SQLAlchemy()
login_manager = LoginManager()
admin = Admin(name='admins')
# security = Security()
mail = Mail()
bootstrap = Bootstrap()

login_manager.login_view = 'security.login'
login_manager.login_message = u"Пожалуйста, авторизируйтесь."
from .forms_security import ExtendedRegisterForm


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    admin.init_app(app, url='/admin', index_view=HomeAdminView(name='Главная'))
    login_manager.init_app(app)
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
    mail.init_app(app)
    bootstrap.init_app(app)

    from .views.main.views import main
    from .views.event.views import events
    from .views.arena.views import arenas
    from .views.artist.views import artists
    from .views.manager.views import managers
    from .views.login.views import logins
    from .views.tour.views import tours
    from .views.api.views import api
    from .views.security.views import security
    from .views.profile.views import profiles
    from .views.message.views import messages
    from .views.friends.views import friends

    app.register_blueprint(main)
    app.register_blueprint(events)
    app.register_blueprint(arenas)
    app.register_blueprint(artists)
    app.register_blueprint(managers)
    app.register_blueprint(tours)
    app.register_blueprint(api)
    app.register_blueprint(security)
    app.register_blueprint(profiles)
    app.register_blueprint(messages)
    app.register_blueprint(friends)

    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    @app.route('/uploads/<filename>')
    def uploaded_file(filename):
        return send_from_directory(app.config['UPLOAD_PHOTO_PROFILES'],
                                   filename)

    @app.route('/photo_profile/<filename>')
    @login_required
    def photo_profile(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_PROFILES,
                                   filename)

    @app.route('/document_profile/<filename>')
    @login_required
    def document_profile(filename):
        return send_from_directory(Config.UPLOAD_DOCUMENTS_PROFILES,
                                   filename)

    @app.route('/img_arena/<img>')
    @login_required
    def img_arena(img):
        return send_from_directory(Config.UPLOAD_PHOTO_ARENA,
                                   img)

    @app.route('/photo_artist/<filename>')
    def photo_artist(filename):
        return send_from_directory(Config.UPLOAD_PHOTO_ARTIST,
                                   filename)

    @app.route('/inspina/<path:filename>')
    def inspina(filename):
        return send_from_directory(Config.UPLOAD_ADMIN,
                                   filename)

    @app.context_processor
    def company_default():
        if current_user.is_authenticated:
            company_default = Company.query.get(current_user.settings.company_default_id)
            if not company_default:
                settings = Settings.query.get(current_user.settings_id)
                settings.company_default_id = current_user.company[0].id
                db.session.commit()
                company_default = Company.query.get(current_user.settings.company_default_id)
            # return dict(company_default=current_user.company[0])
            return dict(company_default=company_default)
        return dict(company_default=None)

    @app.context_processor
    def messages_notifications():
        if current_user.is_authenticated:
            messages_notifications = PrivateMessages.query.filter(PrivateMessages.recipient_id == current_user.id).filter(PrivateMessages.read == False).order_by(PrivateMessages.create.desc()).all()
            return dict(messages_notifications=messages_notifications)
        return dict(messages_notifications=None)

    session_cookie = SecureCookieSessionInterface().get_signing_serializer(app)

    @app.after_request
    def cookies(response):
        same_cookie = session_cookie.dumps(dict(session))
        response.headers.add("Set-Cookie", f"my_cookie={same_cookie}; Secure; HttpOnly; SameSite=None; Path=/;")
        return response

    return app


from .models import *
from .model.equipment import *
from .model.menu import *
from .model.city import *
from .model.security import *

from .openweather import OpenWeather

weather = OpenWeather(appid=Config.APPID, db=db, model=Weather)


class AdminMixIn:
    def is_accessible(self):
        if current_user.is_anonymous:
            return False
        else:
            return 'admin' in current_user.roles

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))


class AdminView(AdminMixIn, ModelView):
    pass


class HomeAdminView(AdminMixIn, AdminIndexView):
    pass


admin.add_view(AdminView(Tour, db.session))
admin.add_view(AdminView(Event, db.session))
admin.add_view(AdminView(Artist, db.session))
admin.add_view(AdminView(Arena, db.session))
admin.add_view(AdminView(TypeHall, db.session))
admin.add_view(AdminView(TypeEvent, db.session))
admin.add_view(AdminView(Menu, db.session))

admin.add_view(AdminView(EquipmentCategory, db.session))
admin.add_view(AdminView(EquipmentSubcategory, db.session))
admin.add_view(AdminView(Equipment, db.session))

admin.add_view(AdminView(Country, db.session))
admin.add_view(AdminView(Region, db.session))
admin.add_view(AdminView(City, db.session))
admin.add_view(AdminView(Weather, db.session))

admin.add_view(AdminView(Document, db.session))
admin.add_view(AdminView(CompanyType, db.session))
admin.add_view(AdminView(Company, db.session))
admin.add_view(AdminView(RolesCompany, db.session))

admin.add_view(AdminView(User, db.session))
admin.add_view(AdminView(Role, db.session))
admin.add_view(AdminView(Confirmation, db.session))
admin.add_view(AdminView(Invite, db.session))
admin.add_view(AdminView(Settings, db.session))
admin.add_view(AdminView(PrivateMessages, db.session))


# user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)


def setup_logger():
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    formatter = logging.Formatter('%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    error_log = Config.LOG_DIR.joinpath('error.log')
    file_heandler = logging.FileHandler(error_log)

    file_heandler.setFormatter(formatter)
    logger.addHandler(file_heandler)

    return logger


logger = setup_logger()


def allowed_photo_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_PHOTO


def allowed_document_profile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_DOCUMENT


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


def generate_id():
    return str(uuid.uuid4())

event/equipment/views.py
from flask import Blueprint, jsonify
from blog import logger, session, docs
from blog.schemas import VideoSchema, UserSchema, AuthSchema, EquimentsSchema
from flask_apispec import use_kwargs, marshal_with
# from blog.models import Equipment, Event
from flask_jwt_extended import jwt_required, get_jwt_identity
from blog.base_view import BaseView

equipments = Blueprint('equipments', __name__)


@equipments.route('/catalog', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list():
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq
@equipments.route('/catalog/<int:light>', methods=['GET'])
# @jwt_required
@marshal_with(EquimentsSchema(many=True))
def get_list_light(light):
    try:
        user_id = get_jwt_identity()
        eq = Equipment.query.filter(Equipment.catalogeqs_id==light).all()
    except Exception as e:
        logger.warning(
            f'user: {user_id} tutorials - read action failed with errors: {e}'
        )
        return {'message': str(e)}, 400
    return eq




@equipments.errorhandler(422)
def error_handler(err):
    headers = err.data.get('headers', None)
    messages = err.data.get('messages', ['Invalid request'])
    if headers:
        return jsonify({'message': messages}), 400, headers
    else:
        return jsonify({'message': messages}), 400


docs.register(get_list, blueprint='equipments')
# docs.register(update_list, blueprint='videos')
# docs.register(update_tutorial, blueprint='videos')
# docs.register(delete_list, blueprint='videos')
# docs.register(get_video, blueprint=videos)
# ListView.register(videos, docs, '/main', 'listview')

event/views/friends/__init__.py
# ----------------------------------------------------
# Program by Andrey Vestimy
#
#
# Version   Date    Info
# 1.0       2020    ----
#
# ----------------------------------------------------

event/views/friends/views.py
from flask import Blueprint, jsonify, request, json, render_template, redirect
from flask import abort
from event import logger, config, allowed_photo_profile
import os
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from flask_security import login_required, current_user
from event.decorators import decorated_admin
from event.forms import *

friends = Blueprint('friends', __name__)


@friends.route('/friends/', methods=['GET'])
@login_required
def index():
    return render_template('mailbox.html')

event/views/security/views.py
from flask import Blueprint, request, render_template, redirect, abort, session
from event import logger, config, allowed_photo_profile, allowed_document_profile, load_user
from event.emails import send_confirm, send_forgot, send_confirm_succes
from event import generate_id
from flask_login import logout_user, login_user, login_required, current_user
from flask import flash, request, redirect, url_for
from werkzeug.utils import secure_filename
from werkzeug.security import check_password_hash, generate_password_hash
from event.forms import *

from event.model.security import *

security = Blueprint('security', __name__)


@security.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('security.login'))


@security.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    login_user_form = LoginForm(request.form)
    email = request.form.get('email')
    password = request.form.get('password')
    if request.method == 'POST' and login_user_form.validate():
        if User.get_email(email):
            user = User.get_email(email)
        elif User.query.filter(User.login == email).first():
            user = User.query.filter(User.login == email).first()
        else:
            user = None
        if user.active:
            if user:
                if check_password_hash(user.password, password):
                    login_user(user)
                    session.permanent = True
                    next_page = request.args.get('next')
                    if next_page is None:
                        return redirect(url_for('main.index'))
                    return redirect(next_page)
                else:
                    flash('Неверый логин или пароль')
            else:
                flash('Пользователь не существует')
        else:
            flash('Пользователь не активирван')
    return render_template('security/login_user.html', login_user_form=login_user_form)


@security.route('/registration', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    role = Role.query.get(2)
    user = User()
    register_user_form = RegisterUserForm(request.form, obj=user)
    password = request.form.get('password')
    password_confirm = request.form.get('password_confirm')
    id = request.args.get('id')
    email = request.args.get('email')
    if id and email:
        register_user_form = RegisterInviteForm(request.form, obj=user)
        invite = Invite.query.filter(Invite.invite_id == id).first()
        if request.method == 'POST' and request.form.get(
                'submit_invite') and invite and invite.email == email:
            if register_user_form.validate():
                if not (login or password or password_confirm):
                    flash('Заполните все поля')
                elif password != password_confirm:
                    flash('Пароли не совпадают')
                else:
                    register_user_form.populate_obj(user)
                    hash_pwd = generate_password_hash(password)
                    user.password = hash_pwd
                    user.email = invite.email
                    user.active = True
                    user.roles.append(role)
                    db.session.add(user)

                    user.company.append(Company.query.get(invite.company_id))
                    settings = Settings(company_default_id=invite.company_id)
                    settings.users.append(user)
                    db.session.add(settings)
                    db.session.delete(invite)
                    db.session.commit()
                    # html = render_template('email_templates/action.html', user=user, id=id, password=password)
                    # send_confirm(user.email, html)
                return redirect(url_for('security.login'))
        return render_template('security/register_invite.html', register_user_form=register_user_form)
    if request.method == 'POST' and register_user_form.validate():
        if not (login or password or password_confirm):
            flash('Заполните все поля')
        elif password != password_confirm:
            flash('Пароли не совпадают')
        else:
            register_user_form.populate_obj(user)
            hash_pwd = generate_password_hash(password)
            user.password = hash_pwd
            user.roles.append(role)
            db.session.add(user)

            id = generate_id()
            confirmation = Confirmation(email=user.email, conf_id=id)
            db.session.add(confirmation)
            db.session.commit()

            html = render_template('email_templates/action.html', user=user, id=id, password=password)
            send_confirm(user.email, html)
        return redirect(url_for('security.login'))
    return render_template('security/register_user.html', register_user_form=register_user_form)


@security.route('/reset', methods=['GET', 'POST'])
def reset():
    form = ForgotPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter(User.email == request.form.get('email')).first()
        html = render_template('email_templates/action.html', user=user)
        send_forgot(request.form.get('email'), html)
    return render_template('security/forgot_password.html', forgot_password_form=form)


@security.route('/confirmation', methods=['GET', 'POST'])
def confirmation():
    company = Company()
    form = CompanyForm(request.form, obj=company)
    email = request.args.get('email')
    id = request.args.get('id')
    if email and id:
        conf_id = Confirmation.query.filter(Confirmation.conf_id == id).first()
        if conf_id and conf_id.email == email:
            user = User.query.filter(User.email == conf_id.email).first()
            if request.method == 'POST':
                form.populate_obj(company)
                db.session.add(company)
                company.creator_id = user.id
                try:
                    company.staff.append(user)
                    company.user_admin.append(user)
                    db.session.commit()
                except Exception as e:
                    logger.warning(
                        f'Подвержение почты: {e}'
                    )
                if company:
                    db.session.delete(conf_id)
                    user.active = True
                    settings = Settings(company_default_id=company.id)
                    settings.users.append(user)
                    db.session.add(settings)
                    db.session.commit()
                html = render_template('email_templates/confirm_successful.html', user=user)
                send_confirm_succes(user.email, html)
                return redirect(url_for('security.login'))
            return render_template('security/confirmation.html', form=form)
    return abort(404)


@security.after_request
def redirect_to_signin(response):
    if response.status_code == 401:
        return redirect(url_for('security.login') + '?2next=' + request.url)
    return response

event/templates/email_templates/action.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Подтверждение email</title>
    <style>
        /* -------------------------------------
    GLOBAL
    A very basic CSS reset
------------------------------------- */
* {
    margin: 0;
    padding: 0;
    font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
    box-sizing: border-box;
    font-size: 14px;
}

img {
    max-width: 100%;
}

body {
    -webkit-font-smoothing: antialiased;
    -webkit-text-size-adjust: none;
    width: 100% !important;
    height: 100%;
    line-height: 1.6;
}

/* Let's make sure all tables have defaults */
table td {
    vertical-align: top;
}

/* -------------------------------------
    BODY & CONTAINER
------------------------------------- */
body {
    background-color: #f6f6f6;
}

.body-wrap {
    background-color: #f6f6f6;
    width: 100%;
}

.container {
    display: block !important;
    max-width: 600px !important;
    margin: 0 auto !important;
    /* makes it centered */
    clear: both !important;
}

.content {
    max-width: 600px;
    margin: 0 auto;
    display: block;
    padding: 20px;
}

/* -------------------------------------
    HEADER, FOOTER, MAIN
------------------------------------- */
.main {
    background: #fff;
    border: 1px solid #e9e9e9;
    border-radius: 3px;
}

.content-wrap {
    padding: 20px;
}

.content-block {
    padding: 0 0 20px;
}

.header {
    width: 100%;
    margin-bottom: 20px;
}

.footer {
    width: 100%;
    clear: both;
    color: #999;
    padding: 20px;
}
.footer a {
    color: #999;
}
.footer p, .footer a, .footer unsubscribe, .footer td {
    font-size: 12px;
}

/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, h2, h3 {
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    color: #000;
    margin: 40px 0 0;
    line-height: 1.2;
    font-weight: 400;
}

h1 {
    font-size: 32px;
    font-weight: 500;
}

h2 {
    font-size: 24px;
}

h3 {
    font-size: 18px;
}

h4 {
    font-size: 14px;
    font-weight: 600;
}

p, ul, ol {
    margin-bottom: 10px;
    font-weight: normal;
}
p li, ul li, ol li {
    margin-left: 5px;
    list-style-position: inside;
}

/* -------------------------------------
    LINKS & BUTTONS
------------------------------------- */
a {
    color: #1ab394;
    text-decoration: underline;
}

.btn-primary {
    text-decoration: none;
    color: #FFF;
    background-color: #1ab394;
    border: solid #1ab394;
    border-width: 5px 10px;
    line-height: 2;
    font-weight: bold;
    text-align: center;
    cursor: pointer;
    display: inline-block;
    border-radius: 5px;
    text-transform: capitalize;
}

/* -------------------------------------
    OTHER STYLES THAT MIGHT BE USEFUL
------------------------------------- */
.last {
    margin-bottom: 0;
}

.first {
    margin-top: 0;
}

.aligncenter {
    text-align: center;
}

.alignright {
    text-align: right;
}

.alignleft {
    text-align: left;
}

.clear {
    clear: both;
}

/* -------------------------------------
    ALERTS
    Change the class depending on warning email, good email or bad email
------------------------------------- */
.alert {
    font-size: 16px;
    color: #fff;
    font-weight: 500;
    padding: 20px;
    text-align: center;
    border-radius: 3px 3px 0 0;
}
.alert a {
    color: #fff;
    text-decoration: none;
    font-weight: 500;
    font-size: 16px;
}
.alert.alert-warning {
    background: #f8ac59;
}
.alert.alert-bad {
    background: #ed5565;
}
.alert.alert-good {
    background: #1ab394;
}

/* -------------------------------------
    INVOICE
    Styles for the billing table
------------------------------------- */
.invoice {
    margin: 40px auto;
    text-align: left;
    width: 80%;
}
.invoice td {
    padding: 5px 0;
}
.invoice .invoice-items {
    width: 100%;
}
.invoice .invoice-items td {
    border-top: #eee 1px solid;
}
.invoice .invoice-items .total td {
    border-top: 2px solid #333;
    border-bottom: 2px solid #333;
    font-weight: 700;
}

/* -------------------------------------
    RESPONSIVE AND MOBILE FRIENDLY STYLES
------------------------------------- */
@media only screen and (max-width: 640px) {
    h1, h2, h3, h4 {
        font-weight: 600 !important;
        margin: 20px 0 5px !important;
    }

    h1 {
        font-size: 22px !important;
    }

    h2 {
        font-size: 18px !important;
    }

    h3 {
        font-size: 16px !important;
    }

    .container {
        width: 100% !important;
    }

    .content, .content-wrap {
        padding: 10px !important;
    }

    .invoice {
        width: 100% !important;
    }
}


    </style>
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="content-wrap">
                            <table cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        <img class="img-fluid"
                                             src="{{ url_for('inspina', filename='email_templates/img/header.jpg', _external = True)}}"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <h3>Добро пожаловать,
                                            {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.login }}{%
                                            endif %}!</h3>

                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        Кем бы ты ни был, откуда бы ты ни был и чем бы ты не занимался ранее, ты попал в
                                        правильное место. Ты находишься на стартовой позиции, как и другие соискатели
                                        TM+, поэтому все в твоих руках.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        Вы зарегистрировались.Пожалуйста, подтвердите ваш email {{ user.email }}.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block aligncenter">
                                        <a href="{{ url_for('security.confirmation', email=user.email, id=id, _external = True) }}"
                                           class="btn-primary">Подтвердить</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
<!--                <div class="footer">-->
<!--                    <table width="100%">-->
<!--                        <tr>-->
<!--                            <td class="aligncenter content-block">Follow <a href="#">@Company</a> on Twitter.</td>-->
<!--                        </tr>-->
<!--                    </table>-->
<!--                </div>-->
            </div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>

event/templates/email_templates/action_user.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Actionable emails e.g. reset password</title>
    <link href="{{ url_for('inspina', filename='styles.css')}}" media="all" rel="stylesheet" type="text/css" />
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="content-wrap">
                            <table  cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        <img class="img-fluid" src="{{ url_for('inspina', filename='img/header.jpg')}}"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <h3>Добро пожаловать, 
                                       </h3>
                                    
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        Кем бы ты ни был, откуда бы ты ни был и чем бы ты не занимался ранее, ты попал в правильное место. Ты находишься на стартовой позиции, как и другие соискатели TM+, поэтому все в твоих руках.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        Вас пригласили, подтвердите ваш email {{ user.email }}.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block aligncenter">
                                        <a href="{{ 'https://' + request.host + url_for('security.register', id=id, email=email) }}" class="btn-primary">Подтвердить</a>
                                    </td>
                                </tr>
                              </table>
                        </td>
                    </tr>
                </table>
                <div class="footer">
                    <table width="100%">
                        <tr>
                            <td class="aligncenter content-block">Follow <a href="#">@Company</a> on Twitter.</td>
                        </tr>
                    </table>
                </div></div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>

event/templates/email_templates/alert.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Alerts e.g. approaching your limit</title>
    <link href="styles.css" media="all" rel="stylesheet" type="text/css" />
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="alert alert-good">
                            Info: You're approaching your limit. Please upgrade.
                        </td>
                    </tr>
                    <tr>
                        <td class="content-wrap">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td class="content-block">
                                        You have <strong>1 free report</strong> remaining.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <a href="#" class="btn-primary">Upgrade my account</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        Thanks for choosing Company Inc.
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <div class="footer">
                    <table width="100%">
                        <tr>
                            <td class="aligncenter content-block"><a href="#">Unsubscribe</a> from these alerts.</td>
                        </tr>
                    </table>
                </div></div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>